# 模型容量
> 拟合各种函数的能力
> 低容量的模型难以拟合训练数据，高容量的模型可以记住所有的训练数据
> 可以用训练误差和泛化误差之间的差距来衡量过拟合和欠拟合
> 模型容量需要匹配数据复杂度，否则可能导致欠拟合和过拟合
<img alt="image.png" height="500" src="/Users/loneker/Desktop/d2l/pic/iShot_2024-04-15_09.53.19.png" width="700"/>

In [1]:
import math
import numpy as np
import torch
from torch import nn
from d2l import torch as d2l

## 使用三阶多项式来生成训练和测试数据的标签
<img alt="image.png" height="100" src="/Users/loneker/Desktop/d2l/pic/iShot_2024-04-15_12.34.13.png" width="700"/>

In [11]:
max_degree = 20     # 多项式的最大阶数
n_train, n_test = 100, 100  # 训练样本和测试样本都是100个
true_w = np.zeros(max_degree)   # 分配大量的空间
true_w[0 : 4] = np.array([5, 1.2, -3.4, 5.6])   # 后面都是噪音项

features = np.random.normal(size = (n_train + n_test, 1))
np.random.shuffle(features)
poly_features = np.power(features, np.arange(max_degree).reshape(1, -1))
for i in range(max_degree):
    poly_features[: i] /= math.gamma(i + 1)
labels = np.dot(poly_features, true_w)
labels += np.random.normal(scale=0.1, size = labels.shape)

In [12]:
true_w, features, poly_features, labels = [torch.tensor(x, dtype=torch.float32) for x in [true_w, features, poly_features, labels]]
features[:2], poly_features[:2, :], labels[:2]

(tensor([[0.2655],
         [1.4631]]),
 tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 tensor([0.0649, 0.0597]))